const products = [
    {
        id: 1,
        title: "Elegant Pearl Necklace",
        category: "Necklaces",
        price: 3499,
        image: "IMAGES/Elegant Pearl Necklace.png",
        description: "Timeless freshwater pearl necklace with a sterling silver clasp. Each pearl is hand-selected for its luster and perfectly round shape. Length: 45cm + 5cm extender. Comes in a luxurious gift box.",
    },
    {
        id: 2,
        title: "Crystal Teardrop Earrings",
        category: "Earrings",
        price: 1899,
        image: "IMAGES/Crystal Teardrop Earrings.png",
        description: "Dazzling teardrop earrings featuring genuine Swarovski crystals. Set in rhodium-plated brass for a brilliant shine. Hypoallergenic posts suitable for sensitive ears. Length: 3.5cm.",
    },
    {
        id: 3,
        title: "Gold Chain Bracelet",
        category: "Bracelets",
        price: 2799,
        image: "IMAGES/Gold Chain Bracelet.png",
        description: "Classic 14k gold-plated chain bracelet with a secure lobster clasp. The delicate Cuban link design adds a touch of everyday elegance. Adjustable length: 17-20cm. Tarnish-resistant finish.",
    },
    {
        id: 4,
        title: "Solitaire Diamond Ring",
        category: "Rings",
        price: 12999,
        image: "IMAGES/Solitaire Diamond Ring.png",
        description: "Stunning solitaire ring with a brilliant-cut cubic zirconia center stone. Set in solid sterling silver with 18k white gold plating. Available in sizes 5-9. Perfect for engagements or special occasions.",
    },
    {
        id: 5,
        title: "Bohemian Beaded Anklet",
        category: "Anklets",
        price: 899,
        image: "IMAGES/Bohemian Beaded Anklet.png",
        description: "Handcrafted anklet featuring colorful semi-precious stones and gold-plated spacers. Adjustable macrame cord fits most ankle sizes. Water-resistant and perfect for beach days.",
    },
    {
        id: 6,
        title: "Heart Locket Pendant",
        category: "Pendants",
        price: 2299,
        image: "IMAGES/Heart Locket Pendant.png",
        description: "Vintage-inspired heart locket in polished sterling silver. Opens to hold two small photos. Includes a 45cm silver chain. A sentimental gift she’ll cherish forever.",
    },
    {
        id: 7,
        title: "Art Deco Brooch",
        category: "Brooches",
        price: 1599,
        image: "IMAGES/Art Deco Brooch.png",
        description: "Exquisite art deco brooch adorned with emerald-colored crystals and delicate filigree work. Gold-tone metal with a secure pin back. Adds a vintage flair to any jacket or dress.",
    },
    {
        id: 8,
        title: "Minimalist Ear Cuffs",
        category: "Earrings",
        price: 1299,
        image: "IMAGES/Minimalist Ear Cuffs.png",
        description: "Set of 3 sterling silver ear cuffs – no piercing required. Modern geometric designs that wrap comfortably around the ear. Lightweight and perfect for stacking.",
    }
];